#include "Empleado.h"
#include "ConexionBD.h"
#include <iostream>
#include <mysql.h>
using namespace std;
Empleado::Empleado() : Persona() { id_empleado = 0; cui = fecha_nacimiento = fecha_inicio_labores = ""; id_puesto = 0; }
Empleado::Empleado(int id, string nom, string ape, string dir, string tel, string cuiEmp, int gen, string fechaNac, int puesto, string fechaInicio) : Persona(nom, ape, dir, tel, gen) { id_empleado = id; cui = cuiEmp; fecha_nacimiento = fechaNac; id_puesto = puesto; fecha_inicio_labores = fechaInicio; }
void Empleado::setIdEmpleado(int id) { id_empleado = id; } void Empleado::setCui(string val) { cui = val; } void Empleado::setFechaNacimiento(string val) { fecha_nacimiento = val; } void Empleado::setIdPuesto(int val) { id_puesto = val; } void Empleado::setFechaInicioLabores(string val) { fecha_inicio_labores = val; }
int Empleado::getIdEmpleado() { return id_empleado; } string Empleado::getCui() { return cui; } string Empleado::getFechaNacimiento() { return fecha_nacimiento; } int Empleado::getIdPuesto() { return id_puesto; } string Empleado::getFechaInicioLabores() { return fecha_inicio_labores; }
void Empleado::crear() { ConexionBD cn; if (!cn.abrirConexion()) return; if (existeCui(cui)) { cout << "ALERTA: el CUI ya existe.\n"; cn.cerrarConexion(); return; } string sql = "INSERT INTO empleados(nombres,apellidos,direccion,telefono,cui,genero,fecha_nacimiento,id_puesto,fecha_inicio_labores,fecha_ingreso) VALUES(" + cn.textoSQL(nombres) + "," + cn.textoSQL(apellidos) + "," + cn.textoSQL(direccion) + "," + cn.textoSQL(telefono) + "," + cn.textoSQL(cui) + ",b'" + to_string(genero) + "'," + cn.textoSQL(fecha_nacimiento) + "," + cn.numeroSQL(id_puesto) + "," + cn.textoSQL(fecha_inicio_labores) + ",NOW())"; if (cn.ejecutar(sql)) cout << "Empleado registrado correctamente.\n"; cn.cerrarConexion(); }
void Empleado::leer() { ConexionBD cn; MYSQL_RES* res; MYSQL_ROW row; if (!cn.abrirConexion()) return; string sql = "SELECT e.id_empleado,e.nombres,e.apellidos,e.telefono,e.cui,BIN(e.genero),p.puesto FROM empleados e INNER JOIN puestos p ON e.id_puesto=p.id_puesto ORDER BY e.id_empleado"; if (mysql_query(cn.getConector(), sql.c_str()) == 0) { res = mysql_store_result(cn.getConector()); cout << "\n===== EMPLEADOS =====\n"; while ((row = mysql_fetch_row(res))) cout << row[0] << " | " << row[1] << " " << row[2] << " | Tel: " << row[3] << " | CUI: " << row[4] << " | Genero: " << row[5] << " | Puesto: " << row[6] << endl; mysql_free_result(res); } else cout << "ALERTA SQL: " << mysql_error(cn.getConector()) << endl; cn.cerrarConexion(); }
void Empleado::actualizar() { ConexionBD cn; if (!cn.abrirConexion()) return; if (!existe(id_empleado)) { cout << "ALERTA: el empleado no existe.\n"; cn.cerrarConexion(); return; } if (existeCui(cui, id_empleado)) { cout << "ALERTA: otro empleado ya tiene ese CUI.\n"; cn.cerrarConexion(); return; } string sql = "UPDATE empleados SET nombres=" + cn.textoSQL(nombres) + ", apellidos=" + cn.textoSQL(apellidos) + ", direccion=" + cn.textoSQL(direccion) + ", telefono=" + cn.textoSQL(telefono) + ", cui=" + cn.textoSQL(cui) + ", genero=b'" + to_string(genero) + "', fecha_nacimiento=" + cn.textoSQL(fecha_nacimiento) + ", id_puesto=" + cn.numeroSQL(id_puesto) + ", fecha_inicio_labores=" + cn.textoSQL(fecha_inicio_labores) + " WHERE id_empleado=" + cn.numeroSQL(id_empleado); if (cn.ejecutar(sql)) cout << "Empleado actualizado correctamente.\n"; cn.cerrarConexion(); }
void Empleado::borrar() { ConexionBD cn; if (!cn.abrirConexion()) return; if (cn.ejecutar("DELETE FROM empleados WHERE id_empleado=" + cn.numeroSQL(id_empleado))) cout << "Empleado eliminado correctamente.\n"; cn.cerrarConexion(); }
bool Empleado::existe(int id) { ConexionBD cn; if (!cn.abrirConexion()) return false; bool r = cn.existe("SELECT id_empleado FROM empleados WHERE id_empleado=" + cn.numeroSQL(id) + " LIMIT 1"); cn.cerrarConexion(); return r; }
bool Empleado::existeCui(string cuiEmp, int id_excluir) { ConexionBD cn; if (!cn.abrirConexion()) return false; string sql = "SELECT id_empleado FROM empleados WHERE cui=" + cn.textoSQL(cuiEmp); if (id_excluir > 0) sql += " AND id_empleado<>" + cn.numeroSQL(id_excluir); sql += " LIMIT 1"; bool r = cn.existe(sql); cn.cerrarConexion(); return r; }
