#include "Producto.h"
#include "ConexionBD.h"
#include <iostream>
#include <mysql.h>
using namespace std;
Producto::Producto() { id_producto=0; producto=descripcion=imagen=""; id_marca=0; precio_costo=precio_venta=0; existencia=0; }
Producto::Producto(int id, string prod, int marca, string desc, string img, double costo, double venta, int stock) { id_producto=id; producto=prod; id_marca=marca; descripcion=desc; imagen=img; precio_costo=costo; precio_venta=venta; existencia=stock; }
void Producto::setIdProducto(int id){id_producto=id;} void Producto::setProducto(string val){producto=val;} void Producto::setIdMarca(int val){id_marca=val;} void Producto::setDescripcion(string val){descripcion=val;} void Producto::setImagen(string val){imagen=val;} void Producto::setPrecioCosto(double val){precio_costo=val;} void Producto::setPrecioVenta(double val){precio_venta=val;} void Producto::setExistencia(int val){existencia=val;}
int Producto::getIdProducto(){return id_producto;} string Producto::getProducto(){return producto;} int Producto::getIdMarca(){return id_marca;} string Producto::getDescripcion(){return descripcion;} string Producto::getImagen(){return imagen;} double Producto::getPrecioCosto(){return precio_costo;} double Producto::getPrecioVenta(){return precio_venta;} int Producto::getExistencia(){return existencia;}
void Producto::crear(){ ConexionBD cn; if(!cn.abrirConexion()) return; string sql="INSERT INTO productos(producto,id_marca,descripcion,imagen,precio_costo,precio_venta,existencia,fecha_ingreso) VALUES("+cn.textoSQL(producto)+","+cn.numeroSQL(id_marca)+","+cn.textoSQL(descripcion)+","+cn.textoSQL(imagen)+","+cn.decimalSQL(precio_costo)+","+cn.decimalSQL(precio_venta)+","+cn.numeroSQL(existencia)+",NOW())"; if(cn.ejecutar(sql)) cout<<"Producto registrado correctamente.\n"; cn.cerrarConexion(); }
void Producto::leer(){ ConexionBD cn; MYSQL_RES* res; MYSQL_ROW row; if(!cn.abrirConexion()) return; string sql="SELECT p.id_producto,p.producto,m.marca,p.precio_costo,p.precio_venta,p.existencia FROM productos p INNER JOIN marcas m ON p.id_marca=m.id_marca ORDER BY p.id_producto"; if(mysql_query(cn.getConector(),sql.c_str())==0){ res=mysql_store_result(cn.getConector()); cout<<"\n===== PRODUCTOS =====\n"; while((row=mysql_fetch_row(res))) cout<<row[0]<<" | "<<row[1]<<" | Marca: "<<row[2]<<" | Costo: Q"<<row[3]<<" | Venta: Q"<<row[4]<<" | Existencia: "<<row[5]<<endl; mysql_free_result(res);} else cout<<"ALERTA SQL: "<<mysql_error(cn.getConector())<<endl; cn.cerrarConexion(); }
void Producto::actualizar(){ ConexionBD cn; if(!cn.abrirConexion()) return; if(!existe(id_producto)){ cout<<"ALERTA: el producto no existe.\n"; cn.cerrarConexion(); return;} string sql="UPDATE productos SET producto="+cn.textoSQL(producto)+", id_marca="+cn.numeroSQL(id_marca)+", descripcion="+cn.textoSQL(descripcion)+", imagen="+cn.textoSQL(imagen)+", precio_costo="+cn.decimalSQL(precio_costo)+", precio_venta="+cn.decimalSQL(precio_venta)+", existencia="+cn.numeroSQL(existencia)+" WHERE id_producto="+cn.numeroSQL(id_producto); if(cn.ejecutar(sql)) cout<<"Producto actualizado correctamente.\n"; cn.cerrarConexion(); }
void Producto::borrar(){ ConexionBD cn; if(!cn.abrirConexion()) return; if(cn.ejecutar("DELETE FROM productos WHERE id_producto="+cn.numeroSQL(id_producto))) cout<<"Producto eliminado correctamente.\n"; cn.cerrarConexion(); }
bool Producto::existe(int id){ ConexionBD cn; if(!cn.abrirConexion()) return false; bool r=cn.existe("SELECT id_producto FROM productos WHERE id_producto="+cn.numeroSQL(id)+" LIMIT 1"); cn.cerrarConexion(); return r; }
double Producto::obtenerPrecioVenta(int id){ ConexionBD cn; if(!cn.abrirConexion()) return 0; double r=cn.obtenerDecimal("SELECT precio_venta FROM productos WHERE id_producto="+cn.numeroSQL(id)); cn.cerrarConexion(); return r; }
int Producto::obtenerExistencia(int id){ ConexionBD cn; if(!cn.abrirConexion()) return 0; int r=cn.obtenerEntero("SELECT existencia FROM productos WHERE id_producto="+cn.numeroSQL(id)); cn.cerrarConexion(); return r; }
bool Producto::descontarInventario(int id,int cantidad){ ConexionBD cn; if(!cn.abrirConexion()) return false; bool r=cn.ejecutar("UPDATE productos SET existencia=existencia-"+cn.numeroSQL(cantidad)+" WHERE id_producto="+cn.numeroSQL(id)+" AND existencia>= "+cn.numeroSQL(cantidad)); cn.cerrarConexion(); return r; }
bool Producto::sumarInventario(int id,int cantidad){ ConexionBD cn; if(!cn.abrirConexion()) return false; bool r=cn.ejecutar("UPDATE productos SET existencia=existencia+"+cn.numeroSQL(cantidad)+" WHERE id_producto="+cn.numeroSQL(id)); cn.cerrarConexion(); return r; }
