#include "Proveedor.h"
#include "ConexionBD.h"
#include <iostream>
#include <mysql.h>
using namespace std;
Proveedor::Proveedor() { id_proveedor = 0; proveedor = nit = direccion = telefono = ""; }
Proveedor::Proveedor(int id, string prov, string nitProv, string dir, string tel) { id_proveedor = id; proveedor = prov; nit = nitProv; direccion = dir; telefono = tel; }
void Proveedor::setIdProveedor(int id) { id_proveedor = id; } void Proveedor::setProveedor(string val) { proveedor = val; } void Proveedor::setNit(string val) { nit = val; } void Proveedor::setDireccion(string val) { direccion = val; } void Proveedor::setTelefono(string val) { telefono = val; }
int Proveedor::getIdProveedor() { return id_proveedor; } string Proveedor::getProveedor() { return proveedor; } string Proveedor::getNit() { return nit; } string Proveedor::getDireccion() { return direccion; } string Proveedor::getTelefono() { return telefono; }
void Proveedor::crear() { ConexionBD cn; if (!cn.abrirConexion()) return; if (existeNit(nit)) { cout << "ALERTA: el NIT del proveedor ya existe.\n"; cn.cerrarConexion(); return; } string sql = "INSERT INTO proveedores(proveedor,nit,direccion,telefono) VALUES(" + cn.textoSQL(proveedor) + "," + cn.textoSQL(nit) + "," + cn.textoSQL(direccion) + "," + cn.textoSQL(telefono) + ")"; if (cn.ejecutar(sql)) cout << "Proveedor registrado correctamente.\n"; cn.cerrarConexion(); }
void Proveedor::leer() { ConexionBD cn; MYSQL_RES* res; MYSQL_ROW row; if (!cn.abrirConexion()) return; string sql = "SELECT id_proveedor,proveedor,nit,direccion,telefono FROM proveedores ORDER BY id_proveedor"; if (mysql_query(cn.getConector(), sql.c_str()) == 0) { res = mysql_store_result(cn.getConector()); cout << "\n===== PROVEEDORES =====\n"; while ((row = mysql_fetch_row(res))) cout << row[0] << " | " << row[1] << " | NIT: " << row[2] << " | " << row[3] << " | " << row[4] << endl; mysql_free_result(res); } else cout << "ALERTA SQL: " << mysql_error(cn.getConector()) << endl; cn.cerrarConexion(); }
void Proveedor::actualizar() { ConexionBD cn; if (!cn.abrirConexion()) return; if (!existe(id_proveedor)) { cout << "ALERTA: el proveedor no existe.\n"; cn.cerrarConexion(); return; } if (existeNit(nit, id_proveedor)) { cout << "ALERTA: otro proveedor tiene ese NIT.\n"; cn.cerrarConexion(); return; } string sql = "UPDATE proveedores SET proveedor=" + cn.textoSQL(proveedor) + ", nit=" + cn.textoSQL(nit) + ", direccion=" + cn.textoSQL(direccion) + ", telefono=" + cn.textoSQL(telefono) + " WHERE id_proveedor=" + cn.numeroSQL(id_proveedor); if (cn.ejecutar(sql)) cout << "Proveedor actualizado correctamente.\n"; cn.cerrarConexion(); }
void Proveedor::borrar() { ConexionBD cn; if (!cn.abrirConexion()) return; if (cn.ejecutar("DELETE FROM proveedores WHERE id_proveedor=" + cn.numeroSQL(id_proveedor))) cout << "Proveedor eliminado correctamente.\n"; cn.cerrarConexion(); }
bool Proveedor::existe(int id) { ConexionBD cn; if (!cn.abrirConexion()) return false; bool r = cn.existe("SELECT id_proveedor FROM proveedores WHERE id_proveedor=" + cn.numeroSQL(id) + " LIMIT 1"); cn.cerrarConexion(); return r; }
bool Proveedor::existeNit(string nitProv, int id_excluir) { ConexionBD cn; if (!cn.abrirConexion()) return false; string sql = "SELECT id_proveedor FROM proveedores WHERE nit=" + cn.textoSQL(nitProv); if (id_excluir > 0) sql += " AND id_proveedor<>" + cn.numeroSQL(id_excluir); sql += " LIMIT 1"; bool r = cn.existe(sql); cn.cerrarConexion(); return r; }
